name: "Docker Build"
on:
  pull_request:
    branches:
      - "main"
jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
<<<<<<< HEAD
          go-version-file: 'go.work'
          cache-dependency-path: "**/*.sum"
=======
          go-version: '1.22.1'
>>>>>>> main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Build
        run: |
          cd opensearch-operator
          make docker-build-multiarch
