name: Test Matrix
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

jobs:
  cluster-helm-chart:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        os-version: [2.13.0, 2.10.0, 2.6.0, 2.3.0, 2.0.1]
        k3s-version: [v1.24, v1.26, v1.29]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.work'
          cache: false
      - uses: nolar/setup-k3d-k3s@v1
        with:
          version: ${{ matrix.k3s-version }}
          k3d-name: opensearch-operator-tests
          k3d-args: --agents 2 -p 30000-30005:30000-30005@agent:0
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          set -e
          export CLUSTER_NAME=opensearch-operator-tests
          ## Check disk to avoid failed shard assignments due to watermarking
          df -h
          cd opensearch-operator
          ## Prepare kubeconfig
          k3d kubeconfig get $CLUSTER_NAME > functionaltests/kubeconfig
          export KUBECONFIG=$(pwd)/functionaltests/kubeconfig

          ## Build controller docker image
          make docker-build

          ## Import controller docker image
          k3d image import -c $CLUSTER_NAME controller:latest

          ## Install helm chart
          helm install opensearch-operator ../charts/opensearch-operator --set manager.image.repository=controller --set manager.image.tag=latest --set manager.image.pullPolicy=IfNotPresent --namespace default --wait
          helm install opensearch-cluster ../charts/opensearch-cluster --set opensearchCluster.general.version=${{ matrix.os-version }}  --set opensearchCluster.dashboards.version=${{ matrix.os-version }} --wait
          cd functionaltests

          ## Run tests
          go test ./helmtests -timeout 15m
